services:
  # Servicio de Tailscale - Configuración mínima
  tailscale:
    image: tailscale/tailscale:latest
    hostname: server-rodolfo
    container_name: tailscale-main
    environment:
      - TS_AUTHKEY=tskey-auth-kNwEyuyuMs11CNTRL-QVbV7bvN4B1Jr9pXa9XNB1Snp9KmRMY6
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=true
      - TS_HOSTNAME=server-rodolfo
    volumes:
      - tailscale_data:/var/lib/tailscale
    restart: unless-stopped
    ports:
      - "3030:3030"
      - "9443:9443"

  # API Node.js
  rc-api:
    build:
      context: ./rc-app-api-v2
      dockerfile: Dockerfile
    container_name: rc-api
    environment:
      - NODE_ENV=production
      - PORT=3030
      - API_HOST=0.0.0.0
      - API_PORT=3030
    volumes:
      - api_data:/app/data
      - ./logs:/app/logs
    network_mode: service:tailscale
    depends_on:
      - tailscale
    restart: unless-stopped

  # Portainer
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock --bind=:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    network_mode: service:tailscale
    depends_on:
      - tailscale
    restart: unless-stopped

volumes:
  tailscale_data:
  api_data:
  portainer_data: