version: "3.8"

services:
  api:
    build: ./api
    container_name: api
    environment:
      - DB_HOST=postgres
      - DB_USER=rctv
      - DB_PASSWORD=rctv@01
      - DB_NAME=media_db
      - DB_PORT=5432
      - PORT=4000
    volumes:
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - postgres
    networks:
      - tunnel-net
    ports:
      - "4000:4000"   # expone API localmente

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: rctv
      POSTGRES_PASSWORD: rctv@01
      POSTGRES_DB: media_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tunnel-net

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"   # expone Portainer en la red local
    networks:
      - tunnel-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run --token ${TUNNEL_TOKEN}
    volumes:
      - ./cloudflared:/etc/cloudflared
    networks:
      - tunnel-net
    depends_on:
      - api
      - portainer

networks:
  tunnel-net:
    driver: bridge

volumes:
  pgdata:
  portainer_data:
