version: "3.8"

services:
  api:
    build: ./api
    container_name: api
    environment:
      - DB_HOST=postgres
      - DB_USER=rctv
      - DB_PASSWORD=rctv@01
      - DB_NAME=media_db
      - DB_PORT=5432
      - PORT=4000
    volumes:
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - postgres
    networks:
      - tunnel-net
    expose:
      - "4000"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: rctv
      POSTGRES_PASSWORD: rctv@01
      POSTGRES_DB: media_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - tunnel-net
    expose:
      - "5432"
