services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale-root
    hostname: server
    environment:
      - TS_AUTHKEY=tskey-auth-kNwEyuyuMs11CNTRL-QVbV7bvN4B1Jr9pXa9XNB1Snp9KmRMY6
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ts-authkey:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    command: >
      sh -c "tailscaled &
            sleep 5 &&
            tailscale up --authkey=$TS_AUTHKEY --hostname=server &&
            tailscale serve https:443 /api http://127.0.0.1:3030 &
            tailscale serve https:443 /portainer http://127.0.0.1:9443 &
            tailscale funnel 443 on &
            wait"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9443:9443"   # puerto publicado al host
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  backend:
    build: ./rc-app-api-v1
    container_name: api-v1
    ports:
      - "3030:3030"   # puerto publicado al host
    restart: unless-stopped

volumes:
  ts-authkey:
    driver: local
  portainer_data:
    driver: local
