version: "3.8"

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: victordoblezz@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Inicio@01
    networks:
      - tunnel-net
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  tunnel-net:

volumes:
  pgadmin_data:
