version: "3.8"

services:
  api:
    build: ./api
    container_name: api
    environment:
      - DB_HOST=postgres
      - DB_USER=rctv
      - DB_PASSWORD=rctv@01
      - DB_NAME=media_db
      - DB_PORT=5432   # 👈 puerto interno de Postgres en Docker
      - PORT=4000
    volumes:
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - postgres
    networks:
      - tunnel-net
    expose:
      - "4000"  # accesible solo dentro de la red Docker

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: rctv
      POSTGRES_PASSWORD: rctv@01
      POSTGRES_DB: media_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - tunnel-net
    ports:
      - "7864:5432"   # 👈 accesible desde fuera del servidor (ej. pgAdmin local)
    expose:
      - "5432"        # accesible dentro de la red Docker

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - tunnel-net
    ports:
      - "9000:9000"   # 👈 expuesto fuera
    expose:
      - "9000"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel run --token "${TUNNEL_TOKEN}"
    volumes:
      - ./cloudflared:/etc/cloudflared
    networks:
      - tunnel-net
    depends_on:
      - api
      - portainer
      - postgres

networks:
  tunnel-net:
    driver: bridge

volumes:
  pgdata:
  portainer_data:
