services:
  tailscale-authkey1:
    image: tailscale/tailscale:latest
    container_name: tailscale-root
    hostname: server
    environment:
      - TS_AUTHKEY=tskey-auth-kNwEyuyuMs11CNTRL-QVbV7bvN4B1Jr9pXa9XNB1Snp9KmRMY6
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ts-authkey:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  nginx-authkey:
    image: nginx
    network_mode: service:tailscale-authkey1

volumes:
  ts-authkey:
    driver: local
