services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: rctv-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: rctv
      POSTGRES_PASSWORD: rctv@01
      POSTGRES_DB: media_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-database.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rctv -d media_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Application
  api:
    build: .
    container_name: rctv-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: rctv
      DB_PASSWORD: rctv@01
      DB_NAME: media_db
      JWT_SECRET: rctv@media
      JWT_EXPIRES_IN: 7d
    volumes:
      - ./media:/app/media
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
